### ISSUE TITLE
services.serving.knative.dev "kn-cli" not found error and I am Unable to disable un secure route for kn-cli

### ISSUE THREAD

**Issue by mabubaker1947** [openshift-knative/serverless-operator#1215]
I am unable to disable unsecure route after installing Red Hat OpenShift Serverless on an OCP v3.1.1 cluster on red hat openshift cloud platform. I have also installed the knative serving and knative eventing successfully on OCP cluster. this is a blocking issues for me as I need to install couple of things on my cluster and the pods for those are in reconciling phase due to this issue. The command I ran is as below:

```
$ oc annotate service.serving.knative.dev/kn-cli -n knative-serving serving.knative.openshift.io/disableRoute=true
Error from server (NotFound): services.serving.knative.dev "kn-cli" not found
``` 
I used to disable this route using the above command on my cluster with same configurations however, right now the command is not working and is returning `Error from server (NotFound): services.serving.knative.dev "kn-cli" not found`
Please note that No pods related to "kn-cli" are running under Knative-serving namesapce.

**Platform Info:**
OCP v4.7.13
Red hat Openshift serverless v1.17.0
Knative-serving v0.23.1
Knative-eventing v0.23.0

**Comment by mabubaker1947** [comment]
@skonto do you know anything about this or know of any workaround there ?

**Comment by marekklofac** [comment]
I have the same issue. The deployment of CP4WAIOps did not go through because of this. The 
IBM Watson AIOps AI Manager Instance is stuck in Phase: Reconciliation due to this. No pods are created, only secrets.

**Comment by markusthoemmes** [comment]
Would you please open a support ticket about this. The Github issue tracker is not an official support vehicle and there's no official engagement done here.

**Comment by mabubaker1947** [comment]
@markusthoemmes please point me in the right direction by sharing the exact link where I can create the ticket and if there any department to tag there for escalation of this issue.

**Comment by nainaz** [comment]
Hello @mabubaker1947 . For product related issues, please reach out to Red Hat Support. 
You can find information on how to connect to Support using various channel(s) here : https://access.redhat.com/support?extIdCarryOver=true&sc_cid=701f2000001OH6kAAG

Please mention OpenShift Serverless as the product .

**Comment by nainaz** [comment]
Oops. Looks like the settings issues in your account  if everything else is valid. 
At this point, I would suggest to call or chat Support to open the ticket for the original issue and get their guidance for access issue. 

I apologize but we really cannot help through this channel.
