### ISSUE TITLE
Changes in KnativeKafka Components in 1.23.0

### ISSUE THREAD

**Issue by nrrso** [openshift-knative/serverless-operator#1635]
In OpenShift Serverless 1.23.0 several changes to KnativeKafka components have been made.

Unfortunately some changes are not communicated inside of the [Release Notes for 1.23.0](https://docs.openshift.com/container-platform/4.8/serverless/serverless-release-notes.html#serverless-rn-1-23-0_serverless-release-notes)

These changes include:
* Refactoring of `kafka-ch-dispatcher` into two components, which are: `kafka-channel-receiver` and `kafka-channel-dispatcher`
* Renaming of the Metrics Labels for `kafka-channel-dispatcher` (see: https://github.com/openshift-knative/serverless-operator/commit/6147a573f032b0312608fd1c2418651d00682b5b?diff=split?diff=split)
* Changes to the KnativeKafka Pod selectors and in general labels, e.g.:
  * `messaging.knative.dev/channel: kafka-channel` to only `app=kafka-channel-dispatcher`
  
 Why is this important?
 We have created for example a set of Custom Grafana Dashboards for our customer and the only way currently to find out if an update breaks our Dashboards and/or custom Prometheus Rules and Monitors, is to check this repository.

**Comment by nainaz** [comment]
Sorry to hear this @nrrso . 
We considered these to be implementation details. 
We will offer some documentation around this as some other folks might face the same challenge. 
May I ask what are the custom dashboards showing? Can we do a follow up  thread/meeting with you on this and it can help us figure out what other dashboards insights we should be doing. My email address is naisingh@redhat.com could you please reach out to me for further discussion about the customer?
