### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by nicknas** [openshift-knative/serverless-operator#1869]
Hello! I would like to know if arm support is on the roadmap.

**Comment by nainaz** [comment]
ARM support is on the Roadmap. Could you open an RFE with the customer use case attached to it? Here is the project https://issues.redhat.com/secure/Dashboard.jspa?selectPageId=12330440 with the component Serverless. That will help us in prioritizing

**Comment by mumi** [comment]
Hey, was this implemented? When I try to install the serverless operator, I get the following ImagePullBackOff errors:

`Failed to pull image "registry.redhat.io/openshift-serverless-1/kn-cli-artifacts-rhel8@sha256:73f0e84235a401319734ab3dd0074533e2364d5043e7afa711ce0c40ca3d71bb": choosing image instance: no image found in manifest list for architecture arm64, variant "v8", OS linux`

`Failed to pull image "registry.redhat.io/openshift-serverless-1/ingress-rhel8-operator@sha256:124c3d5d4d8ff7adb19fe565a8fa26f7577a21b75979171daa0af7b2aa10ac8d": choosing image instance: no image found in manifest list for architecture arm64, variant "v8", OS linux`

`Failed to pull image "registry.redhat.io/openshift-serverless-1/serverless-rhel8-operator@sha256:c92dbaae77f0b415c5d0b1f577ed48624bab2cdee901ad4f1615649b50a3f2de": choosing image instance: no image found in manifest list for architecture arm64, variant "v8", OS linux`
