### ISSUE TITLE
Include trusted-ca-bundle of the OpenShift Cluster in Knative Eventing Deployments

### ISSUE THREAD

**Issue by nrrso** [openshift-knative/serverless-operator#1961]
We are currently using OpenShift Serverless on OCP4.8 with OSS 1.24. As our OpenShift environment sits behind a corporate network with it's own ca, the OpenShift Cluster has been configured to use the Operator Injection as described here:
https://docs.openshift.com/container-platform/4.8/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki

We stumbled upon this issue specifically for the `mt-broker-filter` deployment, as this is the pod that will call the event consumer (which in our case can be outside of the cluster network). Our event consumers usually use self-signed certs issued by a private ca.

Currently we fixed the issue with a workaround, by using `additionalManifests` (see https://knative.dev/docs/install/operator/knative-with-operators/#append-mode) and using our custom deployment yaml, which includes the volume mount. 

The changes done in the custom deployment look similar like these:
```PATCH
diff --git a/config/brokers/mt-channel-broker/deployments/broker-filter.yaml b/config/brokers/mt-channel-broker/deployments/broker-filter.yaml
index 924c132fd..948c26a39 100644
--- a/config/brokers/mt-channel-broker/deployments/broker-filter.yaml
+++ b/config/brokers/mt-channel-broker/deployments/broker-filter.yaml
@@ -37,8 +37,19 @@ spec:
     spec:
       serviceAccountName: mt-broker-filter
       enableServiceLinks: false
+      volumes:
+      - name: trusted-ca
+        configMap:
+          name: trusted-ca
+          items:
+          - key: ca-bundle.crt
+            path: tls-ca-bundle.pem
       containers:
       - name: filter
+        volumeMounts:
+        - name: trusted-ca
+          mountPath: /etc/pki/ca-trust/extracted/pem
+          readOnly: true
         terminationMessagePolicy: FallbackToLogsOnError
         image: ko://knative.dev/eventing/cmd/broker/filter
         readinessProbe: &probe
```

We are opening the issue to share the info and discuss if maybe the `mt-broker-filter` and other consumer facing deployments could automatically mount the configmap, as it seems to be a standard that other Red Hat OpenShift products seem to support.

**Comment by matzew** [comment]
/close
this is now part of serverless 1.32.

We mount such an annotated ConfigMap under `/ocp-serverless-custom-certs` on each eventing workload, unless a custom `SSL_CERT_DIR` is provided.

See proper release notes for details
