### ISSUE TITLE
Fix OLM index image generator to not include higher release version in previous channels 

### ISSUE THREAD

**Issue by dsimansk** [openshift-knative/serverless-operator#2285]
Just a note for the future because we have been setting it wrong for this stable-1.29 channel. It should include versions up to 1.29.x. Not 1.30 or newer.

_Originally posted by @mgencur in https://github.com/openshift-knative/serverless-operator/pull/2283#discussion_r1338023190_

**Comment by pierDipi** [comment]
This is done I believe
