### ISSUE TITLE
TestServerlessUpgrade timeout

### ISSUE THREAD

**Issue by pierDipi** [openshift-knative/serverless-operator#2320]
on https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/2312/pull-ci-openshift-knative-serverless-operator-main-4.13-upgrade-tests-aws-ocp-413/1711419060102631424
```
FAIL test/upgrade.TestServerlessUpgradePrePost/PreUpgradeTests/KafkaBrokerPreUpgradeTest/broker_smoke_test/Requirement (-1.00s)
=== RUN   TestServerlessUpgradePrePost/PreUpgradeTests/InMemoryChannelPreUpgradeTest/ChannelChain/Assert
FAIL test/upgrade.TestServerlessUpgradePrePost/PreUpgradeTests/InMemoryChannelPreUpgradeTest/ChannelChain/Assert (-1.00s)
=== RUN   TestServerlessUpgradePrePost/Run/Steps/PostUpgradeTests/Verify_jobs_in_knative-serving
panic: test timed out after 1h30m0s
```

**Comment by pierDipi** [comment]
Another instance on main https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-knative-serverless-operator-main-4.13-upgrade-tests-aws-ocp-413-continuous/1711562263917236224

**Comment by ReToCode** [comment]
@pierDipi this should now be fine to close?
