### ISSUE TITLE
Adjustable Logging Level for kube-rbac-proxy Container

### ISSUE THREAD

**Issue by VikramVuppla** [openshift-knative/serverless-operator#2740]
Currently, the log level of the `kube-rbac-proxy` container is set to 10 (_--v=10_), which logs sensitive information such as tokens to the logs.

```
  kube-rbac-proxy:
    Image:         registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:a6ea11d4df5b439e6ceaf8e9f8799a56aee1cfbfad774af968e01c1e175514c0
    Image ID:      registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:a6ea11d4df5b439e6ceaf8e9f8799a56aee1cfbfad774af968e01c1e175514c0
    Port:          <none>
    Host Port:     <none>
    Args:
      --secure-listen-address=0.0.0.0:8444
      --upstream=http://127.0.0.1:9090/
      --tls-cert-file=/etc/tls/private/tls.crt
      --tls-private-key-file=/etc/tls/private/tls.key
      --logtostderr=true
      --http2-disable
      --v=10
```

I couldn't find a method to update the args information via Custom Resource (CR). It would be greatly beneficial if support could be added to adjust the log level of the `kube-rbac-proxy` container. Please let me know if you need any additional information.

**Comment by VikramVuppla** [comment]
Hi @skonto, I noticed you contributed to [Support kube rbac proxy overrides](https://github.com/openshift-knative/serverless-operator/pull/1890), is it possible to override the args for `kube-rbac-proxy`? Any help is appreciated, thank you.

**Comment by skonto** [comment]
I think this is related to https://github.com/kubernetes-sigs/kubebuilder/issues/2434
