### ISSUE TITLE
ci/prow/4.5-upgrade-tests-aws-ocp-45 failing: "serverless-operator.v1.6.0" not found

### ISSUE THREAD

**Issue by hemanrnjn** [openshift-knative/serverless-operator#282]
Refer to the build logs [here ](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/277/pull-ci-openshift-knative-serverless-operator-master-4.5-upgrade-tests-aws-ocp-45/279)

ci run link associated with pull request [https://github.com/openshift-knative/serverless-operator/pull/277](https://github.com/openshift-knative/serverless-operator/pull/277)

**Comment by markusthoemmes** [comment]
Tracked in JIRA.
