### ISSUE TITLE
ci/prow/4.5-e2e-aws-ocp-45 fails: "serverless-operator.v1.7.0 is not in desired state"

### ISSUE THREAD

**Issue by hemanrnjn** [openshift-knative/serverless-operator#283]
Refer to the build logs [here](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/277/pull-ci-openshift-knative-serverless-operator-master-4.5-e2e-aws-ocp-45/270)

ci run link associated with pull request [https://github.com/openshift-knative/serverless-operator/pull/277](https://github.com/openshift-knative/serverless-operator/pull/277)

**Comment by markusthoemmes** [comment]
Tracked in JIRA.
