### ISSUE TITLE
unable to curl kservice on openshift

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift-knative/serverless-operator#285]
Here's what I did to install openshift serverless-operator on my openshift 4.3.9 cluster:

1. Create knative-serving project
2. Install openshift serverless operator 1.2.0
3. Go to serverless operator in knative-serving ns and ‘Create Knative Serving’ then ‘Create’

I then wait for the pods in knative-serving to come up successfully. I'm able to [create a knative service](https://raw.githubusercontent.com/SeldonIO/seldon-core/b1f4d96a11d76d8aa9ef73dd74f428e666277205/components/drift-detection/cifar10/message-dumper.yaml) and it says it is ready:
```
NAME             URL                                                      LATESTCREATED          LATESTREADY            READY   REASON
message-dumper   http://message-dumper.seldon.apps.clive1.seldondev.com   message-dumper-fjh2d   message-dumper-fjh2d   True    
```
The pod is running and I tail its logs as I hope to see output there when I curl it. I deploy a curler pod [like in some of the demos](https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-eventing/eventing-trigger-broker.html) and curl the status url but it does not hit the service and I get html back:

```
      <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>

      <div class="alert alert-info">
        <p class="info">
          Possible reasons you are seeing this page:
        </p>
        <ul>
          <li>
            <strong>The host doesn't exist.</strong>
            Make sure the hostname was typed correctly and that a route matching this hostname exists.
          </li>
          <li>
            <strong>The host exists, but doesn't have a matching path.</strong>
            Check if the URL path was typed correctly and that the route was created using the desired path.
          </li>
          <li>
            <strong>Route and path matches, but all pods are down.</strong>
            Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
          </li>
        </ul>

```
Have also tried the [greeter example ](https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/basic-fundas.html) and the request just hangs. The greeter is up and running but the request never reaches it.

I see a user-container and a queue-proxy in  the pods. Wondering if I should also be seeing istio sidecars. I do have RedHat Openshift Service Mesh installed and the namespace is in the member roll. Am able to use istio in the namespace to route traffic through virtualservices (without knative) and that works fine. Not sure what I should be doing to configure knative correctly.

**Comment by markusthoemmes** [comment]
Is there any reason you're still using the 1.2.0 release of the serverless operator? We're meanwhile on 1.6.0 with a ton of improvements being made, including a streamlined setup experience.

Please note: 1.2.0 was a Tech Preview release. We're meanwhile on 1.6.0 and strongly encourage to upgrade to that. There's no official support for 1.2.0 at this point.

**Comment by ryandawsonuk** [comment]
Oh sorry I put the wrong number above. I am actually using 1.6.0:

![image](https://user-images.githubusercontent.com/22754674/80466155-0a293980-8934-11ea-8d7c-f91f5c3301f9.png)

**Comment by markusthoemmes** [comment]
I suspect the ServiceMesh being the issue here. Reaching out via Slack, will report back once we got to the bottom of it.

**Comment by ryandawsonuk** [comment]
Turns out this is an incompatibility with the Service Mesh operator (v1.1.0). Following the suggestion of @markusthoemmes, I removed the namespace I was using from the mesh MemberRoll. The greeter example then started working. As I understand there's currently no way to use the serverless operator together with mesh, at least if both are active in the same namespace.

**Comment by ryandawsonuk** [comment]
Closing this ticket in favour of https://github.com/openshift-knative/serverless-operator/issues/286

**Comment by ryandawsonuk** [comment]
FWIW, I am able to run the greeter example if I install [istio using the istio-provided OpenShift instructions](https://istio.io/docs/setup/platform-setup/openshift/) rather than using the OpenShift Service Mesh version, at least when running without sidecar injection (not tried with sidecar injection).
