### ISSUE TITLE
"status.version" in knativeserving.operator.knative.dev is not accurate and confusable

### ISSUE THREAD

**Issue by nak3** [openshift-knative/serverless-operator#361]
### Version

HEAD (Build on eaafb3e47e29f83af4455fc26ad22f8222325904)

### Issue

I can get following version

```
$ oc get knativeserving.operator.knative.dev  -n knative-serving
NAME              VERSION   READY   REASON
knative-serving   0.14.0    True
```

It is from  https://github.com/openshift-knative/serverless-operator/blob/069dc2a2bd029b658d1ebd76440f5c229e981b06/knative-operator/vendor/knative.dev/operator/version/version.go#L5

But the serving code is v0.14.1 as per https://github.com/openshift-knative/serverless-operator/commit/22598fa59e0686cae80eee0a6dcf331fb1029adb.

**Comment by markusthoemmes** [comment]
Ugh, we might need to make sure we update `version.go` in the operator, I might've forgotten that :see_no_evil:

**Comment by skonto** [comment]
Same applies to eventing:
```
$ ./oc  get knativeeventing.operator.knative.dev  -n knative-eventing
NAME               VERSION   READY   REASON
knative-eventing   0.14.2    True   ```

**Comment by markusthoemmes** [comment]
I believe this is no longer an issue. Please reopen if it is.
