### ISSUE TITLE
CSV version bump has problems when knative version is not bumped

### ISSUE THREAD

**Issue by matzew** [openshift-knative/serverless-operator#362]
Looking here:
https://github.com/openshift-knative/serverless-operator/pull/359#issuecomment-651765032

it seems that bumping the CVS version _BUT_ not the knative version is not possible.

However there are use-cases when you want to have a new CSV/Operator version, but wanna keep the knative version same (E.g. rebuild based on base image fixes/improvements)

**Comment by matzew** [comment]
/cc @markusthoemmes @mgencur 

Starting to capture "known" issues, so we have them

**Comment by nak3** [comment]
I think this https://github.com/openshift-knative/serverless-operator/pull/360 will fix this issue.
