### ISSUE TITLE
Some dependencies are still Knative 0.14

### ISSUE THREAD

**Issue by nak3** [openshift-knative/serverless-operator#426]
The dependencies should be updated to 0.15, but following packages have Knative 0.15.

- test/Gopkg.tomltest/Gopkg.toml
https://github.com/openshift-knative/serverless-operator/blob/master/test/Gopkg.toml#L36-L50

- serving/ingress/Gopkg.toml
https://github.com/openshift-knative/serverless-operator/blob/master/serving/ingress/Gopkg.toml#L46-L52

I don't see any specific issue for now, but remember that they were updated in previous version like https://github.com/openshift-knative/serverless-operator/commit/a833c6c7b83bc972b808ef8cf36668c2011c71a3

**Comment by rhuss** [comment]
I'm not aware of any issues either, so +1 from me to update the dependendcies

**Comment by markusthoemmes** [comment]
Yeah, feel free to bump.
