### ISSUE TITLE
Update Operator to use Knative 0.16 and increase OLM metadata to 1.10.0

### ISSUE THREAD

**Issue by matzew** [openshift-knative/serverless-operator#437]
In theory this is done via a few steps:

- [x] Bumping the OLM version to 1.10 (https://github.com/openshift-knative/serverless-operator/pull/438)
- [ ] Updating to `knative/client` fork version `release-0.16` bits
- [ ] Updating to `knative/serving` fork version `release-0.16` bits
- [ ] Updating to `knative/eventing` fork version `release-0.16` bits
- [ ] Updating to `knative/operator` fork version `release-0.16` bits
- [ ] Updating Golang dependencies for Operator to `release-0.16` bits

**Comment by markusthoemmes** [comment]
I believe this is done?
