### ISSUE TITLE
docs for using with service mesh (istio)

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift-knative/serverless-operator#891]
Could docs be provided for using with service mesh (istio)? Or a link to existing docs if there are some?

See https://github.com/openshift-knative/serverless-operator/issues/286#issuecomment-745121368

**Comment by markusthoemmes** [comment]
@ryandawsonuk see https://docs.openshift.com/container-platform/4.7/serverless/networking/serverless-ossm.html

**Comment by ryandawsonuk** [comment]
Thanks for the quick reply
