### ISSUE TITLE
Update yq version

### ISSUE THREAD

**Issue by nak3** [openshift-knative/serverless-operator#939]
This project expects yq v3 like https://github.com/openshift-knative/serverless-operator/blob/main/.github/workflows/validate.yaml#L28 but it is too old version and I need to switch v3 and v4 in my local env :sweat_smile: 

Is there any blocker to update yq version to v4?

**Comment by skonto** [comment]
@markusthoemmes is the migration to yq postponed? What are the next steps? Should we capture it here?

**Comment by skonto** [comment]
@nak3 according to Markus work the migration was a bit too invasive. Should we close this for now or try to push forward the work? WDYTH?

**Comment by nak3** [comment]
Yes, let's close this.
